version: "3"

services:
  docker-blinkt:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: shadash/docker-blinkt:latest
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
